project: example
inputs:
  remotes:
    # Replace document_id with the id of your document or remove if not used
    gsheets_url: https://docs.google.com/spreadsheets/d/1iSc-kmNEtHJ-jjAN8QFRgJaHpqIVTmjY-nkzHQqRKsQ
    mappings:
      - sheet: Characters
        table: characters.csv
  templates:
    mappings:
      - table: characters.csv
        template: character.tex
outputs:
  pdflatex:
    mainfile: main.tex
    variants:
      - name: reference
        class: fancy
      - name: printable
        class: printable
  imposer:
    halfpage: true
    booklet: true